# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('avatar', models.CharField(default='static/images/default.png', max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('createtime', models.DateField(auto_now=True)),
            ],
        ),
    ]
